Move temporary dir deletion to inner function, delete temp dir in skipped benchmarks
redis/redis-benchmarks-specification pull request #248
Opened 2023-09-04 13:18 UTC by mpozniak95

Opened again from branch created in this repository instead of forked branch.

Probably connected with issue: https://github.com/redis/redis-benchmarks-specification/issues/244.

So far when some check resulted with skipping benchmark, it would keep an empty temporary directory in home directory. Deletion of temporary dir should happen in such situation before continuing to the next benchmark.

This PR moves temporary directory deletion to inner function in process_self_contained_coordinator_stream and invokes it before skipping any benchmark

2023-09-12 11:57 UTC, mpozniak95 commented on redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
> -                                            stdout=True, stderr=True, logs=True
Also there was an issue with this line in contained_coordinator. When benchmark raised an exception for any reason we tried to print container logs but it resulted with: `TypeError: ContainerApiMixin.logs() got an unexpected keyword argument 'logs'`. According to https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.Container.logs parameter `logs `for method `logs()` doesn't exist. This led to skipping 'teardown' stage which led to temporary folders being left with the redis-server artifact inside.

2023-09-13 09:29 UTC, mpozniak95 commented on redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
> -                                            stdout=True, stderr=True, logs=True
With that change instead we get:
```
2023-09-13 01:33:49 CRITICAL Some unexpected exception was caught during local work. Failing test....
2023-09-13 01:33:49 CRITICAL <class 'KeyError'>
2023-09-13 01:33:49 INFO Tearing down setup
2023-09-13 01:33:49 INFO When trying to stop DB container with id a9b45d05a8ba306464d79d3d0deeaa2a72dd7d8761b838aefe5d318326e1cf5e and image <Image: 'debian:buster'> it was already stopped
2023-09-13 01:33:49 INFO Removing temporary dirs /root/tmp7rhog4yu and /root/tmpkcu7fzqu
```
And temporary dirs are removed

2023-09-13 11:38 UTC, markovamaria requested changes
Hi Marcin, thank you for PR!

Could you please fix integration test failure? This is failing - test_run_local_command_logic_oss_cluster  according to log. 

You can use these PRs for test's run reference: 
- https://github.com/redis/redis-benchmarks-specification/pull/211
- https://github.com/redis/redis-benchmarks-specification/pull/216

Let me know in case of questions.

2023-09-14 06:17 UTC, mpozniak95 commented
I think that that wasn't fault of my PR, there was an "Connection Refused" exception when trying to connect to Redis. I re-run test and it worked.

2023-09-14 10:06 UTC, markovamaria approved these changes

2023-09-14 10:06 UTC, markovamaria commented
@filipecosta90 , could you please check and merge if you are agree?

2023-09-29 18:20 UTC, merged